import re
import sys
from pathlib import Path


def main():
    # Load links
    sites_dot_path = Path(sys.argv[1])
    links: [tuple[int, int]] = []
    with sites_dot_path.open('rt') as sites_dot:
        for line in sites_dot:
            line = line.strip()
            if (match := re.match(r"(\d+) -- (\d+)", line)) is None:
                continue
            links.append(tuple([int(v, 10) for v in match.groups()]))

    # Write CPP definition file.
    out_path = Path(sys.argv[2])
    with out_path.open('w') as out:
        indent = ""
        out.write(f"/* THIS FILE IS AUTOMATICALLY GENERATED */\n")
        out.write("\n")
        out.write("#include <vector>\n")
        out.write("#include \"FnSite.h\"\n")
        out.write("\n")
        out.write(f"{indent}const std::vector<std::array<FnSite::Id, 2>> FnSite::kAllLinks {{\n")
        indent = "    "
        for link in links:
            out.write(
                f"{indent}{{{link[0]}, {link[1]}}},\n"
            )
        indent = ""
        out.write(f"{indent}}};\n")


if __name__ == "__main__":
    main()
