/**
 * @file themeIcon.cpp
 *
 * @author Dan Keenan
 * @date 12/28/24
 * @copyright GNU GPLv3
 */

#include "themeIcon.h"
#include <unordered_map>

QIcon qIconFromTheme(ThemeIcon iconName) {
#if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
  static std::unordered_map<ThemeIcon, QString> kThemeIcons{
      {ThemeIcon::AddressBookNew, "address-book-new"},
      {ThemeIcon::ApplicationExit, "application-exit"},
      {ThemeIcon::AppointmentNew, "appointment-new"},
      {ThemeIcon::CallStart, "call-start"},
      {ThemeIcon::CallStop, "call-stop"},
      {ThemeIcon::ContactNew, "contact-new"},
      {ThemeIcon::DocumentNew, "document-new"},
      {ThemeIcon::DocumentOpen, "document-open"},
      {ThemeIcon::DocumentOpenRecent, "document-open-recent"},
      {ThemeIcon::DocumentPageSetup, "document-page-setup"},
      {ThemeIcon::DocumentPrint, "document-print"},
      {ThemeIcon::DocumentPrintPreview, "document-print-preview"},
      {ThemeIcon::DocumentProperties, "document-properties"},
      {ThemeIcon::DocumentRevert, "document-revert"},
      {ThemeIcon::DocumentSave, "document-save"},
      {ThemeIcon::DocumentSaveAs, "document-save-as"},
      {ThemeIcon::DocumentSend, "document-send"},
      {ThemeIcon::EditClear, "edit-clear"},
      {ThemeIcon::EditCopy, "edit-copy"},
      {ThemeIcon::EditCut, "edit-cut"},
      {ThemeIcon::EditDelete, "edit-delete"},
      {ThemeIcon::EditFind, "edit-find"},
      {ThemeIcon::EditPaste, "edit-paste"},
      {ThemeIcon::EditRedo, "edit-redo"},
      {ThemeIcon::EditSelectAll, "edit-select-all"},
      {ThemeIcon::EditUndo, "edit-undo"},
      {ThemeIcon::FolderNew, "folder-new"},
      {ThemeIcon::FormatIndentLess, "format-indent-less"},
      {ThemeIcon::FormatIndentMore, "format-indent-more"},
      {ThemeIcon::FormatJustifyCenter, "format-justify-center"},
      {ThemeIcon::FormatJustifyFill, "format-justify-fill"},
      {ThemeIcon::FormatJustifyLeft, "format-justify-left"},
      {ThemeIcon::FormatJustifyRight, "format-justify-right"},
      {ThemeIcon::FormatTextDirectionLtr, "format-text-direction-ltr"},
      {ThemeIcon::FormatTextDirectionRtl, "format-text-direction-rtl"},
      {ThemeIcon::FormatTextBold, "format-text-bold"},
      {ThemeIcon::FormatTextItalic, "format-text-italic"},
      {ThemeIcon::FormatTextUnderline, "format-text-underline"},
      {ThemeIcon::FormatTextStrikethrough, "format-text-strikethrough"},
      {ThemeIcon::GoDown, "go-down"},
      {ThemeIcon::GoHome, "go-home"},
      {ThemeIcon::GoNext, "go-next"},
      {ThemeIcon::GoPrevious, "go-previous"},
      {ThemeIcon::GoUp, "go-up"},
      {ThemeIcon::HelpAbout, "help-about"},
      {ThemeIcon::HelpFaq, "help-faq"},
      {ThemeIcon::InsertImage, "insert-image"},
      {ThemeIcon::InsertLink, "insert-link"},
      {ThemeIcon::InsertText, "insert-text"},
      {ThemeIcon::ListAdd, "list-add"},
      {ThemeIcon::ListRemove, "list-remove"},
      {ThemeIcon::MailForward, "mail-forward"},
      {ThemeIcon::MailMarkImportant, "mail-mark-important"},
      {ThemeIcon::MailMarkRead, "mail-mark-read"},
      {ThemeIcon::MailMarkUnread, "mail-mark-unread"},
      {ThemeIcon::MailMessageNew, "mail-message-new"},
      {ThemeIcon::MailReplyAll, "mail-reply-all"},
      {ThemeIcon::MailReplySender, "mail-reply-sender"},
      {ThemeIcon::MailSend, "mail-send"},
      {ThemeIcon::MediaEject, "media-eject"},
      {ThemeIcon::MediaPlaybackPause, "media-playback-pause"},
      {ThemeIcon::MediaPlaybackStart, "media-playback-start"},
      {ThemeIcon::MediaPlaybackStop, "media-playback-stop"},
      {ThemeIcon::MediaRecord, "media-record"},
      {ThemeIcon::MediaSeekBackward, "media-seek-backward"},
      {ThemeIcon::MediaSeekForward, "media-seek-forward"},
      {ThemeIcon::MediaSkipBackward, "media-skip-backward"},
      {ThemeIcon::MediaSkipForward, "media-skip-forward"},
      {ThemeIcon::ObjectRotateLeft, "object-rotate-left"},
      {ThemeIcon::ObjectRotateRight, "object-rotate-right"},
      {ThemeIcon::ProcessStop, "process-stop"},
      {ThemeIcon::SystemLockScreen, "system-lock-screen"},
      {ThemeIcon::SystemLogOut, "system-log-out"},
      {ThemeIcon::SystemSearch, "system-search"},
      {ThemeIcon::SystemReboot, "system-reboot"},
      {ThemeIcon::SystemShutdown, "system-shutdown"},
      {ThemeIcon::ToolsCheckSpelling, "tools-check-spelling"},
      {ThemeIcon::ViewFullscreen, "view-fullscreen"},
      {ThemeIcon::ViewRefresh, "view-refresh"},
      {ThemeIcon::ViewRestore, "view-restore"},
      {ThemeIcon::WindowClose, "window-close"},
      {ThemeIcon::WindowNew, "window-new"},
      {ThemeIcon::ZoomFitBest, "zoom-fit-best"},
      {ThemeIcon::ZoomIn, "zoom-in"},
      {ThemeIcon::ZoomOut, "zoom-out"},

      {ThemeIcon::AudioCard, "audio-card"},
      {ThemeIcon::AudioInputMicrophone, "audio-input-microphone"},
      {ThemeIcon::Battery, "battery"},
      {ThemeIcon::CameraPhoto, "camera-photo"},
      {ThemeIcon::CameraVideo, "camera-video"},
      {ThemeIcon::CameraWeb, "camera-web"},
      {ThemeIcon::Computer, "computer"},
      {ThemeIcon::DriveHarddisk, "drive-harddisk"},
      {ThemeIcon::DriveOptical, "drive-optical"},
      {ThemeIcon::InputGaming, "input-gaming"},
      {ThemeIcon::InputKeyboard, "input-keyboard"},
      {ThemeIcon::InputMouse, "input-mouse"},
      {ThemeIcon::InputTablet, "input-tablet"},
      {ThemeIcon::MediaFlash, "media-flash"},
      {ThemeIcon::MediaOptical, "media-optical"},
      {ThemeIcon::MediaTape, "media-tape"},
      {ThemeIcon::MultimediaPlayer, "multimedia-player"},
      {ThemeIcon::NetworkWired, "network-wired"},
      {ThemeIcon::NetworkWireless, "network-wireless"},
      {ThemeIcon::Phone, "phone"},
      {ThemeIcon::Printer, "printer"},
      {ThemeIcon::Scanner, "scanner"},
      {ThemeIcon::VideoDisplay, "video-display"},

      {ThemeIcon::AppointmentMissed, "appointment-missed"},
      {ThemeIcon::AppointmentSoon, "appointment-soon"},
      {ThemeIcon::AudioVolumeHigh, "audio-volume-high"},
      {ThemeIcon::AudioVolumeLow, "audio-volume-low"},
      {ThemeIcon::AudioVolumeMedium, "audio-volume-medium"},
      {ThemeIcon::AudioVolumeMuted, "audio-volume-muted"},
      {ThemeIcon::BatteryCaution, "battery-caution"},
      {ThemeIcon::BatteryLow, "battery-low"},
      {ThemeIcon::DialogError, "dialog-error"},
      {ThemeIcon::DialogInformation, "dialog-information"},
      {ThemeIcon::DialogPassword, "dialog-password"},
      {ThemeIcon::DialogQuestion, "dialog-question"},
      {ThemeIcon::DialogWarning, "dialog-warning"},
      {ThemeIcon::FolderDragAccept, "folder-drag-accept"},
      {ThemeIcon::FolderOpen, "folder-open"},
      {ThemeIcon::FolderVisiting, "folder-visiting"},
      {ThemeIcon::ImageLoading, "image-loading"},
      {ThemeIcon::ImageMissing, "image-missing"},
      {ThemeIcon::MailAttachment, "mail-attachment"},
      {ThemeIcon::MailUnread, "mail-unread"},
      {ThemeIcon::MailRead, "mail-read"},
      {ThemeIcon::MailReplied, "mail-replied"},
      {ThemeIcon::MediaPlaylistRepeat, "media-playlist-repeat"},
      {ThemeIcon::MediaPlaylistShuffle, "media-playlist-shuffle"},
      {ThemeIcon::NetworkOffline, "network-offline"},
      {ThemeIcon::PrinterPrinting, "printer-printing"},
      {ThemeIcon::SecurityHigh, "security-high"},
      {ThemeIcon::SecurityLow, "security-low"},
      {ThemeIcon::SoftwareUpdateAvailable, "software-update-available"},
      {ThemeIcon::SoftwareUpdateUrgent, "software-update-urgent"},
      {ThemeIcon::SyncError, "sync-error"},
      {ThemeIcon::SyncSynchronizing, "sync-synchronizing"},
      {ThemeIcon::UserAvailable, "user-available"},
      {ThemeIcon::UserOffline, "user-offline"},
      {ThemeIcon::WeatherClear, "weather-clear"},
      {ThemeIcon::WeatherClearNight, "weather-clear-night"},
      {ThemeIcon::WeatherFewClouds, "weather-few-clouds"},
      {ThemeIcon::WeatherFewCloudsNight, "weather-few-clouds-night"},
      {ThemeIcon::WeatherFog, "weather-fog"},
      {ThemeIcon::WeatherShowers, "weather-showers"},
      {ThemeIcon::WeatherSnow, "weather-snow"},
      {ThemeIcon::WeatherStorm, "weather-storm"},
  };
  return QIcon::fromTheme(kThemeIcons.at(iconName));
#else
  return QIcon::fromTheme(iconName);
#endif
}
