name: CMake on Ubuntu Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev qt6-svg-dev libboost-all-dev libspdlog-dev cmake build-essential git ninja-build

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare Artifacts
      run: |
        mkdir dist
        cp ${{github.workspace}}/build/src/xenoprobes/xenoprobes dist/
        cp ${{github.workspace}}/build/src/xenoprobes_gui/xenoprobes_gui dist/
        cp ${{github.workspace}}/sites.csv dist/
        cp ${{github.workspace}}/sample-inventory.csv dist/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        path: dist/
        if-no-files-found: error
